//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kursowa
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salary
    {
        public long id_salary { get; set; }
        public long employee_id { get; set; }
        public System.DateTime salary_date { get; set; }
        public decimal sum { get; set; }
        public decimal oved { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
